"""Build the blog for embedding in a Webflow site, and a local mock of it.

Webflow pages carry the site's own styles and scripts, so the self-contained
pages from ``build.py`` cannot be pasted in as they are. This script writes,
to ``webflow/``:

- ``blog.css``: ``src/style.css`` scoped under ``.bac-post``, without the
  dark theme, the theme toggle and the page-level rules;
- ``blog.js``: chart data and the three chart scripts in one file. It does
  nothing on pages without a ``.bac-post`` element, so it can be loaded
  site-wide, and it adds ``blog.css`` (from next to itself) to the page before
  drawing, so the site needs only this one script;
- ``diagrams/<hash>.svg``: the inline SVG diagrams as files, in the light
  colours, because Webflow's editor strips inline SVG;
- ``<page>.body.html``: each page's body and notes inside
  ``<div class="bac-post">``, without the header (the CMS item has its own
  title and author), with the diagrams as ``<img>``;
- ``<page>.rich.html``: the same body split into rich-text embed blocks of at
  most ``EMBED_LIMIT`` characters, for the CMS rich-text field. Webflow's
  editor leaves the blocks alone when someone edits the text around them.

Diagram ``src`` URLs point at jsDelivr serving ``webflow/`` from this
repository at ``--asset-ref`` (default ``main``; ``webflow_api.py push`` builds
with a pinned tag instead). Links between the pages stay ``part-1.html`` etc.
here; ``push`` rewrites them to the posts' URLs.

With ``--mock POST`` it also writes a local mock: the saved HTML of a
published Webflow post (``POST``) with its title and rich-text body replaced
by ours and the two assets linked, so style clashes show up before anything
is uploaded. The mock goes outside the repository (default
``bac-webflow-mock`` in the system temporary directory) because it contains
the site's markup.

Usage (from the repository root, standard library only)::

    python assets/blog/webflow.py
    python assets/blog/webflow.py --check
    python assets/blog/webflow.py --mock saved-post.html
"""

import argparse
import hashlib
import html
import json
import re
import sys
import tempfile
from html.parser import HTMLParser
from pathlib import Path

import build

OUT = build.HERE / "webflow"
SCOPE = ".bac-post"
DATA_LOOKUP = 'JSON.parse(document.getElementById("blog-data-{i}").textContent)'
ASSET_BASE = (
    "https://cdn.jsdelivr.net/gh/Syntheme/beyond-answer-confidence@{ref}"
    "/assets/blog/webflow/"
)
# Webflow's limit on one rich-text embed block, with some margin.
EMBED_LIMIT = 9_800
EMBED = "<div data-rt-embed-type='true'><div class=\"bac-post\">{}</div></div>"
VOID_TAGS = frozenset(
    {
        "area",
        "br",
        "col",
        "embed",
        "hr",
        "img",
        "input",
        "link",
        "meta",
        "source",
        "wbr",
    }
)

# Selectors replaced by the wrapper itself; None drops the selector.
PAGE_SELECTORS: dict[str, str | None] = {
    ":root": SCOPE,
    "body": SCOPE,
    "html": None,
    "main": None,
}

# Appended after the scoped rules: take the site's text font, and undo the
# Webflow rich-text rules that shrink figures to 60%, hide text in figure
# divs, border captions and paint paragraphs white. They tie on specificity
# with ours, so this file must load after the site's stylesheet.
OVERRIDES = "\n".join(
    f"{SCOPE} {rule}"
    for rule in (
        "{ font-family: inherit; background: transparent; }",
        "figure { max-width: none; }",
        "figure div { color: inherit; font-size: inherit; }",
        "figcaption { border-left: 0; padding-left: 0; text-align: left; }",
        "p { background-color: transparent; }",
        ".resource-links { margin: 0 0 24px; }",
        ".diagram img { display: block; width: 100%; height: auto; min-width: 620px; }",
    )
)

RICH_TEXT = re.compile(r'<div class="text-rich-text w-richtext">')
HERO_TITLE = re.compile(r'(<h1 class="hero-v2_heading[^"]*">).*?(</h1>)', re.S)
HEADER = re.compile(r"\s*<header>.*?</header>", re.S)
RESOURCES = re.compile(r'<div class="resource-links">.*?</div>', re.S)
SVG = re.compile(r"<svg\b([^>]*)>.*?</svg>", re.S)
CSS_VAR = re.compile(r"var\((--[a-z0-9-]+)\)")
PAGE_LINK = re.compile(r'href="([a-z0-9-]+\.html)(#[^"]*)?"')

# Wraps the chart scripts: run once the document is parsed, only on pages
# with the post, and only after blog.css (next to this script) has loaded,
# so charts measure themselves with the final styles.
JS_HEAD = """/* Generated by assets/blog/webflow.py; do not edit. */
(() => {
  const script = document.currentScript;
  const start = () => {
    if (!document.querySelector(".bac-post")) return;
    window.BAC_BLOG_DATA = %s;
    const draw = () => {
"""
JS_TAIL = """
    };
    if (!script || !script.src || document.querySelector("link[data-bac-post]")) {
      draw();
      return;
    }
    const link = document.createElement("link");
    link.rel = "stylesheet";
    link.href = new URL("blog.css", script.src).href;
    link.dataset.bacPost = "";
    link.onload = link.onerror = draw;
    document.head.appendChild(link);
  };
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", start);
  } else {
    start();
  }
})();
"""


def scope_selector(sel: str) -> str | None:
    """Scope one selector under the wrapper.

    Args:
        sel: A single selector (no commas).

    Returns:
        The scoped selector, or None if it should be dropped.
    """
    sel = sel.strip()
    if "data-theme" in sel or "theme-toggle" in sel:
        return None
    if sel in PAGE_SELECTORS:
        return PAGE_SELECTORS[sel]
    return f"{SCOPE} {sel}"


def scope_css(css: str) -> str:
    """Scope every rule of a stylesheet under the wrapper.

    Handles plain rules and ``@media`` blocks (recursively); comments are
    removed. Rules left without a selector are dropped.

    Args:
        css: Stylesheet text.

    Returns:
        The scoped stylesheet, one rule per line.
    """
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    out: list[str] = []
    pos = 0
    while (start := css.find("{", pos)) != -1:
        prelude = " ".join(css[pos:start].split())
        depth, end = 1, start + 1
        while depth:
            depth += {"{": 1, "}": -1}.get(css[end], 0)
            end += 1
        inner = css[start + 1 : end - 1]
        pos = end
        if prelude.startswith("@"):
            nested = scope_css(inner)
            if nested:
                out.append(f"{prelude} {{\n{nested}\n}}")
            continue
        sels = [s for s in map(scope_selector, prelude.split(",")) if s]
        if sels:
            decls = " ".join(inner.split())
            out.append(f"{', '.join(dict.fromkeys(sels))} {{ {decls} }}")
    return "\n".join(out)


def bundle_js() -> str:
    """Chart data and chart scripts as one script.

    Returns:
        JavaScript that, on pages with the post, loads ``blog.css``, defines
        the data and draws every chart.

    Raises:
        BuildError: If a chart script does not read its data as expected.
    """
    data = {
        i: json.loads(build.blob(build.CHARTS / f"data-{i}.json")) for i in (1, 2, 3)
    }
    parts = []
    for i in (1, 2, 3):
        code = build.read(build.CHARTS / f"charts-{i}.js").strip()
        lookup = DATA_LOOKUP.format(i=i)
        if code.count(lookup) != 1:
            raise build.BuildError(f"charts-{i}.js: expected one {lookup}")
        parts.append(code.replace(lookup, f"window.BAC_BLOG_DATA[{i}]"))
    head = JS_HEAD % json.dumps(data, separators=(",", ":"))
    return head + "\n".join(parts) + JS_TAIL


def light_colours(css: str) -> dict[str, str]:
    """The light theme's custom properties.

    Args:
        css: ``src/style.css``.

    Returns:
        Value by property name (``--ink`` etc.), from the first ``:root`` rule.

    Raises:
        BuildError: If the stylesheet has no ``:root`` rule.
    """
    m = re.search(r":root\s*\{(.*?)\}", css, re.S)
    if not m:
        raise build.BuildError("style.css has no :root rule")
    return dict(re.findall(r"(--[a-z0-9-]+)\s*:\s*([^;]+);", m.group(1)))


def extract_diagrams(
    body: str, colours: dict[str, str], base: str
) -> tuple[str, dict[str, str]]:
    """Replace inline SVG diagrams with images of standalone SVG files.

    Args:
        body: Page body.
        colours: Custom property values to resolve ``var(--x)`` with.
        base: URL prefix of the ``webflow/`` directory.

    Returns:
        The body, and SVG file text by path relative to ``webflow/``.

    Raises:
        BuildError: If a diagram uses an unknown custom property or has no
            ``viewBox`` or ``aria-label``.
    """
    files: dict[str, str] = {}

    def image(m: re.Match[str]) -> str:
        attrs = m.group(1)
        box = re.search(r'viewBox="0 0 (\d+) (\d+)"', attrs)
        label = re.search(r'aria-label="([^"]*)"', attrs)
        if not box or not label:
            raise build.BuildError("diagram SVG needs viewBox and aria-label")
        unknown = set(CSS_VAR.findall(m.group())) - set(colours)
        if unknown:
            raise build.BuildError(f"diagram uses unknown colour(s) {sorted(unknown)}")
        svg = CSS_VAR.sub(lambda v: colours[v.group(1)], m.group())
        svg = svg.replace(
            "<svg",
            '<svg xmlns="http://www.w3.org/2000/svg" font-family="system-ui, '
            '-apple-system, &quot;Segoe UI&quot;, sans-serif"',
            1,
        )
        name = f"diagrams/{hashlib.sha256(svg.encode()).hexdigest()[:12]}.svg"
        files[name] = svg + "\n"
        return (
            f'<img src="{base}{name}" alt="{label.group(1)}" width="{box.group(1)}" '
            f'height="{box.group(2)}" loading="lazy">'
        )

    return SVG.sub(image, body), files


class _TopLevel(HTMLParser):
    """Offsets of the elements directly inside the outermost element."""

    def __init__(self, text: str) -> None:
        super().__init__(convert_charrefs=False)
        self.depth = 0
        self.starts: list[int] = []
        self.line_starts = [0]
        for line in text.splitlines(keepends=True):
            self.line_starts.append(self.line_starts[-1] + len(line))

    def _mark(self) -> None:
        if self.depth == 1:
            line, col = self.getpos()
            self.starts.append(self.line_starts[line - 1] + col)

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        self._mark()
        if tag not in VOID_TAGS:
            self.depth += 1

    def handle_startendtag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        self._mark()

    def handle_endtag(self, tag: str) -> None:
        if tag not in VOID_TAGS:
            self.depth -= 1


def embed_blocks(body: str, limit: int = EMBED_LIMIT) -> str:
    """Split a ``.bac-post`` body into rich-text embed blocks.

    Blocks break only between the wrapper's direct children, and each block
    gets its own ``.bac-post`` wrapper.

    Args:
        body: Body HTML, one ``<div class="bac-post">`` element.
        limit: Maximum characters per block, wrapper included.

    Returns:
        The blocks, separated by newlines.

    Raises:
        BuildError: If a single child is too large for one block.
    """
    inner_start, inner_end = body.index(">") + 1, body.rindex("</div>")
    parser = _TopLevel(body)
    parser.feed(body)
    cuts = [s for s in parser.starts if inner_start < s < inner_end] + [inner_end]
    room = limit - len(EMBED.format(""))
    blocks: list[str] = []
    start = prev = inner_start
    for cut in cuts:
        if cut - start > room:
            if prev == start:
                raise build.BuildError(
                    f"element at {start} is larger than {room} characters"
                )
            blocks.append(body[start:prev])
            start = prev
        prev = cut
    blocks.append(body[start:inner_end])
    for b in blocks:
        if len(b) > room:
            raise build.BuildError(f"element is larger than {room} characters")
    return "\n".join(EMBED.format(b.strip()) for b in blocks) + "\n"


def page_links(body: str, urls: dict[str, str]) -> str:
    """Point links to other pages at their published URLs.

    Args:
        body: Page body.
        urls: URL by page file name (``part-2.html`` etc.).

    Returns:
        The body with ``href="part-2.html#x"`` turned into ``href="URL#x"``.

    Raises:
        BuildError: If a link names a page without a URL.
    """

    def url(m: re.Match[str]) -> str:
        if m.group(1) not in urls:
            raise build.BuildError(f"no URL for linked page {m.group(1)}")
        return f'href="{html.escape(urls[m.group(1)])}{m.group(2) or ""}"'

    return PAGE_LINK.sub(url, body)


def bodies(
    base: str, urls: dict[str, str] | None = None
) -> tuple[dict[str, str], dict[str, str]]:
    """Each page's body and notes, ready for a rich-text field.

    Args:
        base: URL prefix of the ``webflow/`` directory, for diagram images.
        urls: Published URL by page file name, for links between the pages
            (default: leave them as file names).

    Returns:
        Body HTML by page file name (``index.html`` etc.), and the diagram
        files by path relative to ``webflow/``.
    """
    notes = build.load_notes()
    colours = light_colours(build.read(build.SRC / "style.css"))
    out: dict[str, str] = {}
    files: dict[str, str] = {}
    for p in build.PAGES:
        body, items, _ = build.assemble(p, notes)
        links = RESOURCES.search(body)
        body = HEADER.sub("", body, count=1)
        if links:
            body = f"    {links.group()}\n{body}"
        if urls is not None:
            body = page_links(body, urls)
        body, svgs = extract_diagrams(body, colours, base)
        files |= svgs
        out[p.filename] = (
            f'<div class="bac-post">\n{body}\n    <ol class="notes">\n{items}\n'
            "    </ol>\n</div>\n"
        )
    return out, files


def mock(post: str, body: str, title: str) -> str:
    """Put our title, body and assets into a saved Webflow post.

    Args:
        post: HTML of a published Webflow post.
        body: Our body HTML.
        title: Our title.

    Returns:
        The mock page's HTML.

    Raises:
        BuildError: If the post has no hero title or rich-text body.
    """
    m = RICH_TEXT.search(post)
    if not m or not HERO_TITLE.search(post):
        raise build.BuildError("saved post has no hero title or rich-text body")
    depth, end = 1, m.end()
    for tag in re.finditer(r"<(/?)div\b[^>]*>", post[m.end() :]):
        depth += -1 if tag.group(1) else 1
        if depth == 0:
            end = m.end() + tag.start()
            break
    post = post[: m.end()] + body + post[end:]
    post = HERO_TITLE.sub(
        lambda t: t.group(1) + html.escape(title) + t.group(2), post, count=1
    )
    return post.replace("</head>", '<script src="blog.js" defer></script></head>', 1)


def build_files(
    base: str, urls: dict[str, str] | None = None
) -> tuple[dict[str, str], dict[str, str]]:
    """Every file of the Webflow build.

    Args:
        base: URL prefix of the ``webflow/`` directory, for diagram images.
        urls: Published URL by page file name (see ``bodies``).

    Returns:
        File text by path relative to ``webflow/``, and the ``.rich.html``
        text by page file name.
    """
    files = {
        "blog.css": scope_css(build.read(build.SRC / "style.css"))
        + "\n"
        + OVERRIDES
        + "\n",
        "blog.js": bundle_js(),
    }
    pages, diagrams = bodies(base, urls)
    files |= diagrams
    rich = {}
    for name, text in pages.items():
        rich[name] = embed_blocks(text)
        files[name.replace(".html", ".body.html")] = text
        files[name.replace(".html", ".rich.html")] = rich[name]
    return files, rich


def main(argv: list[str] | None = None) -> int:
    """Command-line entry point.

    Args:
        argv: Arguments (default: ``sys.argv[1:]``).

    Returns:
        Process exit code.
    """
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--mock", type=Path, help="saved HTML of a Webflow post")
    parser.add_argument(
        "--mock-dir",
        type=Path,
        default=Path(tempfile.gettempdir()) / "bac-webflow-mock",
        help="where the mock goes",
    )
    parser.add_argument(
        "--asset-ref", default="main", help="git ref jsDelivr serves the assets from"
    )
    parser.add_argument(
        "--check", action="store_true", help="fail if a file in webflow/ is out of date"
    )
    args = parser.parse_args(argv)
    try:
        files = build_files(ASSET_BASE.format(ref=args.asset_ref))[0]
        mock_pages = bodies("")[0] if args.mock else {}
    except build.BuildError as err:
        sys.stderr.write(f"webflow build: {err}\n")
        return 2
    if args.check:
        stale = sorted(
            name
            for name, text in files.items()
            if not (OUT / name).exists() or build.read(OUT / name) != text
        )
        expected = {OUT / name for name in files}
        stale += sorted(
            str(f.relative_to(OUT))
            for f in OUT.rglob("*")
            if f.is_file() and f not in expected
        )
        if stale:
            sys.stderr.write(
                f"webflow build: out of date: {', '.join(stale)}; "
                "run python assets/blog/webflow.py\n"
            )
            return 1
        return 0
    for name, text in files.items():
        (OUT / name).parent.mkdir(parents=True, exist_ok=True)
        (OUT / name).write_text(text, encoding="utf-8")
        sys.stdout.write(
            f"wrote {(OUT / name).relative_to(build.HERE)} ({len(text) // 1024} KB)\n"
        )
    if args.mock:
        post = args.mock.read_text(encoding="utf-8")
        args.mock_dir.mkdir(parents=True, exist_ok=True)
        for name, text in files.items():
            if not name.endswith(".html"):
                (args.mock_dir / name).parent.mkdir(parents=True, exist_ok=True)
                (args.mock_dir / name).write_text(text, encoding="utf-8")
        for p in build.PAGES:
            page = mock(post, mock_pages[p.filename], p.title)
            (args.mock_dir / p.filename).write_text(page, encoding="utf-8")
        sys.stdout.write(f"mock in {args.mock_dir}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
